version: 1

# APIの許可
apis:
  profiles:
    sales_orders_api:
      base_url: "https://api.example.com/orders"
      timeout_sec: 30
      certificate:
        provider: windows_certificate_store
        store_location: CurrentUser
        store_name: My
        subject_contains: "CN=sales-api-client"

# WEB閲覧の許可
web:
  allowlist:
    - domain: "fonts.google.com"
      path_prefixes:
        - /icons
    - domain: "app.slack.com"
      path_prefixes:
        - /client
    - domain: "www.google.com"
      path_prefixes:
        - /
    - domain: "note.com/"
      path_prefixes:
        - /